AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudEventTrace Function URL Configuration
Globals:
  Function:
    Architectures:
    - x86_64
    Runtime: java11
    MemorySize: 1792
    Timeout: 900
Resources:
  CloudEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-lambda
      Description: Lambda function
      PackageType: Zip
      Handler: lambda.Entry::handleRequest
      FunctionUrlConfig:
        AuthType: NONE
      LoggingConfig:
        LogFormat: Text
        LogGroup:
          Ref: LogGroup
      CodeUri: s3://deployment.testing.bucket/13ac21c48c96151e85d45e59a542dbcb
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/${AWS::StackName}
      RetentionInDays: 14
Outputs:
  FunctionUrl:
    Description: Lambda Function URL
    Value:
      Fn::GetAtt:
      - CloudEventFunctionUrl
      - FunctionUrl
  FunctionArn:
    Description: Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CloudEventFunction
      - Arn
